// Command tool_catalog dumps every built-in tool's Name / Description /
// InputSchema as a Markdown document. Used to keep
// docs/api/tools-catalog.md in sync with the implementation — re-run
// when tools are added or their schemas change.
//
// Usage:
//
//	go run ./cmd/tool_catalog > docs/api/tools-catalog.md
//
// The program shares the same instantiation paths as cmd/server/main.go
// (same constructors, same default configs) so the dumped schemas match
// what the LLM actually receives at runtime.
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"

	"go.uber.org/zap"

	"harnessclaw-go/internal/agent"
	"harnessclaw-go/internal/command"
	"harnessclaw-go/internal/config"
	"harnessclaw-go/internal/skill"
	"harnessclaw-go/internal/task"
	"harnessclaw-go/internal/tool"
	"harnessclaw-go/internal/tool/askuserquestion"
	"harnessclaw-go/internal/tool/bash"
	"harnessclaw-go/internal/tool/fileedit"
	"harnessclaw-go/internal/tool/fileread"
	"harnessclaw-go/internal/tool/filewrite"
	"harnessclaw-go/internal/tool/glob"
	"harnessclaw-go/internal/tool/grep"
	"harnessclaw-go/internal/tool/listloadedskills"
	"harnessclaw-go/internal/tool/loadskill"
	"harnessclaw-go/internal/tool/metatool"
	"harnessclaw-go/internal/tool/plantool"
	"harnessclaw-go/internal/tool/promotetool"
	"harnessclaw-go/internal/tool/searchskill"
	"harnessclaw-go/internal/tool/skilltool"
	"harnessclaw-go/internal/tool/submittool"
	"harnessclaw-go/internal/tool/tasktool"
	"harnessclaw-go/internal/tool/tavilysearch"
	"harnessclaw-go/internal/tool/unloadskill"
	"harnessclaw-go/internal/tool/webfetch"
	"harnessclaw-go/internal/tool/websearch"
	"harnessclaw-go/internal/workspace"
)

func main() {
	logger := zap.NewNop()

	tools := []tool.Tool{
		bash.New(config.ToolConfig{Enabled: true, Timeout: 60_000_000_000, Sandbox: false}),
		fileread.New(config.ToolConfig{Enabled: true}),
		fileedit.New(config.ToolConfig{Enabled: true}),
		filewrite.New(config.ToolConfig{Enabled: true}),
		grep.New(config.ToolConfig{Enabled: true}),
		glob.New(config.ToolConfig{Enabled: true}),
		webfetch.New(config.ToolConfig{Enabled: true}, logger),
		websearch.New(config.WebSearchConfig{Enabled: true, APIKey: "dummy", Limit: 5}, logger),
		tavilysearch.New(config.TavilySearchConfig{Enabled: true, APIKey: "dummy", MaxResults: 5}, logger),
		askuserquestion.New(logger),
		submittool.New(),
		submittool.NewEscalate(),
		// Local-files-as-truth trio. Schema-only context, so a throwaway
		// registry rooted at "" is enough — the catalog never executes
		// these tools.
		plantool.NewPlanUpdateTool(workspace.NewPlanWriterRegistry(""), ""),
		plantool.NewPlanReadTool(""),
		metatool.NewMetaWriteTool(""),
		promotetool.NewPromoteTool(workspace.NewPlanWriterRegistry(""), "", nil),
	}

	// Skill management family. Use empty readers so the catalog reflects
	// schema only — no live skill data needed.
	skillReader := skill.NewReader(nil, logger)
	cmdRegistry := command.NewRegistry()
	tools = append(tools,
		skilltool.New(cmdRegistry, logger),
		searchskill.New(skillReader, logger),
		loadskill.New(skillReader, logger),
		unloadskill.New(logger),
		listloadedskills.New(logger),
	)

	// Task tools (TODO-list management). Use an in-memory sqlite store
	// — we only need the tools for schema dumping, never invoke them.
	taskStore, err := task.NewSQLiteStore(":memory:")
	if err != nil {
		fmt.Fprintf(os.Stderr, "open task store: %v\n", err)
		os.Exit(1)
	}
	defer taskStore.Close()
	scope := "catalog"
	tools = append(tools,
		tasktool.NewCreate(taskStore, scope),
		tasktool.NewGet(taskStore, scope),
		tasktool.NewList(taskStore, scope),
		tasktool.NewUpdate(taskStore, scope),
	)

	// Stable order: alphabetical by Name() for diff-friendly output.
	sort.Slice(tools, func(i, j int) bool { return tools[i].Name() < tools[j].Name() })

	// Header.
	fmt.Println("# 工具目录")
	fmt.Println()
	fmt.Println("> Auto-generated by `cmd/tool_catalog`. Re-run after tool changes:")
	fmt.Println("> ")
	fmt.Println("> ```")
	fmt.Println("> go run ./cmd/tool_catalog > docs/api/tools-catalog.md")
	fmt.Println("> ```")
	fmt.Println()
	fmt.Printf("本文档列出 engine 在启动时注册的全部 %d 个工具（不含 Agent / Specialists / Orchestrate / Team 这类 dispatch 工具——它们需要 engine 实例才能构造，schema 见各自源文件）。\n", len(tools))
	fmt.Println()
	fmt.Println("---")
	fmt.Println()

	// TOC.
	fmt.Println("## 索引")
	fmt.Println()
	for _, t := range tools {
		fmt.Printf("- [%s](#%s)\n", t.Name(), toAnchor(t.Name()))
	}
	fmt.Println()
	fmt.Println("---")
	fmt.Println()

	// Per-tool entries.
	for _, t := range tools {
		dumpTool(t)
	}

	// Dispatch + Team note (these need engine, not dumpable here).
	fmt.Println("## 派活 / 团队管理工具（需 engine 上下文构造，下面只列基本信息）")
	fmt.Println()
	dispatches := []struct{ name, file, desc string }{
		{"task", "internal/tool/agenttool/agenttool.go", "通用 sub-agent 派活工具。指定 `subagent_type`（writer/researcher/analyst/developer/freelancer）+ 任务 prompt。"},
		{"specialists", "internal/tool/specialists/specialists.go", "L2 dispatcher。emma 把整段需求交给它，内部按任务挑合适的 L3 sub-agent。"},
		{"orchestrate", "internal/tool/orchestrate/orchestrate.go", "多步 plan 编排：一次性派多个有依赖关系的 sub-agent。"},
		{"team_create", "internal/tool/teamtool/create.go", "动态创建 team（一组协作 sub-agent + 共享 broker channel）。"},
		{"team_delete", "internal/tool/teamtool/delete.go", "销毁指定 team，回收资源。"},
		{"send_message", "internal/tool/sendmessage/sendmessage.go", "team 内 agent 间消息收发（仅 team 上下文可用）。"},
	}
	for _, d := range dispatches {
		fmt.Printf("### `%s`\n\n", d.name)
		fmt.Printf("**Source**: `%s`\n\n", d.file)
		fmt.Printf("%s\n\n", d.desc)
	}
}

func dumpTool(t tool.Tool) {
	fmt.Printf("## `%s`\n\n", t.Name())

	// Description (escape pipes / heading markers to keep markdown safe).
	desc := t.Description()
	if desc != "" {
		fmt.Println("**Description**:")
		fmt.Println()
		fmt.Println("```")
		fmt.Println(desc)
		fmt.Println("```")
		fmt.Println()
	}

	// Metadata row.
	fmt.Println("| 属性 | 值 |")
	fmt.Println("|---|---|")
	fmt.Printf("| read-only | %v |\n", t.IsReadOnly())
	fmt.Printf("| concurrency-safe | %v |\n", t.IsConcurrencySafe())
	fmt.Printf("| enabled (default) | %v |\n", t.IsEnabled())
	if cr, ok := t.(tool.ClientRoutedTool); ok && cr.IsClientRouted() {
		fmt.Println("| client-routed | true |")
	}
	if lr, ok := t.(tool.LongRunningTool); ok && lr.IsLongRunning() {
		fmt.Println("| long-running | true |")
	}
	if dm, ok := t.(tool.DestructiveMarker); ok && dm.IsDestructive(nil) {
		fmt.Println("| destructive | true |")
	}
	fmt.Println()

	// InputSchema as pretty JSON.
	schema := t.InputSchema()
	if schema != nil {
		b, _ := json.MarshalIndent(schema, "", "  ")
		fmt.Println("**Input Schema**:")
		fmt.Println()
		fmt.Println("```json")
		fmt.Println(string(b))
		fmt.Println("```")
		fmt.Println()
	}
	fmt.Println("---")
	fmt.Println()
}

// toAnchor mimics GitHub's markdown heading anchor algorithm: lower-case
// + non-alphanumeric → -.
func toAnchor(s string) string {
	out := make([]rune, 0, len(s))
	for _, r := range s {
		switch {
		case r >= 'A' && r <= 'Z':
			out = append(out, r+32)
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			out = append(out, r)
		case r == '_' || r == '-':
			out = append(out, r)
		default:
			// drop everything else (matches GH)
		}
	}
	return string(out)
}

// Compile-time check that we depended on agent only for builds where the
// package is referenced elsewhere.
var _ = agent.SpawnConfig{}
